### ISSUE TITLE
HIPAA Wording on the Website

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#10]
https://www.zerionsoftware.com/iformbuilder/

On the above link by Unmatched security we speak about HIPAA I know we got some pushback from some groups in the past about us not being hippa certified so was wondering if we should hold this out from the site.

This may be a question for Scott Hunter

**Comment by truth3** [comment]
@benjaminray3 I am closing this as we do have answers for HIPAA and have sunk a lot of time and energy into it.
