### ISSUE TITLE
Remove Gate Gourmet logo

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#12]
Per Al Rude, we need to obtain written permission to use Gate Gourmet logo on our website. He is going to ask legal today to start the permission process, but in the meantime we need to take it off the site.

**Comment by truth3** [comment]
@eeghbal Said this is done, and I no longer see them on the home page

**Comment by benjaminray3** [comment]
@eeghbal @truth3 Do we need to get permission from all the other companies we have on our site as well? If so do we have that permission from them?

**Comment by truth3** [comment]
@benjaminray3 I think we are OK to leave things be. If someone has an issue, we can respond like we did with Al. I'm pretty sure we are OK to use it as long as no one asks us not to.

**Comment by benjaminray3** [comment]
OK Sounds good. doing my cautionary thinking :)
