### ISSUE TITLE
Contact details

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#15]
Hey @eeghbal I see you killed my `mailto:` links 😆  

![screen shot 2017-01-12 at 5 18 23 pm](https://cloud.githubusercontent.com/assets/7986768/21910771/7f116b20-d8eb-11e6-8983-33b583708d49.png)

What do you think about having these be links to hubspot forms instead? This will deter spambots sniffing web pages, and also takes care of the default mail application issue when using the `mailto` function.

What do ya think?

**Comment by truth3** [comment]
@benjaminray3

**Comment by benjaminray3** [comment]
I would rather not have our direct emails on here. Have them fill out a simple contact us form would suffice here

**Comment by eeghbal** [comment]
@benjaminray3 my hesitation with a form is that anytime someone wants to get in contact with us they have to go to the website. 
@truth3 hm, a lot of websites list email addresses on their contact page (usually the right way: abc@123.com, not abc (@) 123.com) so let me see if there's anything out there about writing it in a way that will deter bots.

**Comment by truth3** [comment]
From the SEO toolbox suite I am using to clean up the site

In order to pass this test you must make your email addresses invisible to email spiders. Note that the best option is to replace your entire contact mechanism with a contact form and using the POST method while submitting the form. Other solutions are listed below:
replace the at (@) and dot (.) characters
replace text with images
use email obfuscators
hide email addresses using JavaScript or CSS trick

**Comment by truth3** [comment]
@eeghbal I am going to mark this closed as one of the recommended solutions is what you did.
