### ISSUE TITLE
White Dot on background image when looking at mobile site

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#16]
There is a white dot in the background image. This should be removed. This seems to only happen for me on my iphone.

![img_6981](https://cloud.githubusercontent.com/assets/7995899/21966445/3817cba8-db41-11e6-9a84-a0b0f3a81df9.PNG)

**Comment by truth3** [comment]
I did a little digging, and was able to track it down to this. I removed it using developer tools and the words still change, so I think we should be OK to just delete this part and fix it.

![screen shot 2017-01-17 at 12 18 49 pm](https://cloud.githubusercontent.com/assets/7986768/22031613/27248894-dcaf-11e6-99f3-6d1e5b1d1449.png)

**Comment by truth3** [comment]
I solved this by removing the background video behind the slider (which wasn't paying on mobile safari). This should help us with site load time as well

![screen shot 2017-01-28 at 12 23 15 pm](https://cloud.githubusercontent.com/assets/7986768/22398356/a7493972-e554-11e6-9a88-41352bed1f5a.png)
