### ISSUE TITLE
Mobile Site - On Pricing Page the Company logos that we have are cut off partially

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#17]
Need to look at these images and make sure they look good on the mobile site. 

![img_6984](https://cloud.githubusercontent.com/assets/7995899/21967002/6b366b92-db4c-11e6-9406-0cb2bd0a5c75.PNG)

**Comment by truth3** [comment]
Removed the logos carosel from this page. I reviewed a number of other sites (hubspot, salesforce, zendesk, fulcrum, and a few others) and none had customer logos on pricing page. This also reduces the height of the page and makes the pricing information visible without scrolling on a laptop and mobile.
