### ISSUE TITLE
Blog pop-up has iFB in the graphic

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#35]
When you are reading a blog article you will get asked to subscribe and in the pop-up there is some artwork which still includes iFormBuilder.

![screen shot 2017-03-01 at 11 32 42 am](https://cloud.githubusercontent.com/assets/7986768/23469878/eb8c52d6-fe72-11e6-9d6f-0fbeb7d73ead.png)

**Comment by truth3** [comment]
Hey @eeghbal any news from Kit on this?

**Comment by eeghbal** [comment]
@truth3 haven't it to him yet - he's finishing up some other stuff this weekend so I'll probably give it to him next week. This is also something I might be able to do (need to look at the ebooks again)
