### ISSUE TITLE
Documents Section needs to be added to  this page

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#38]
https://www.zerionsoftware.com/

On our main website page at the bottom when it says Imagine your data in motion we need to look at adding Documents to this list of services and  quick 1 sentence about it. (See screenshot for where I am talking about)

![screen shot 2017-03-02 at 10 38 35 pm](https://cloud.githubusercontent.com/assets/7995899/23537313/1e62b25a-ff99-11e6-8059-8dc859f4a4dc.png)

**Comment by benjaminray3** [comment]
We need to add a new Blob here.

Here is what I propose

"Documents"

'Put your documents to work for you. Merge any data to a Custom Document and deliver to multiple sources"

@eeghbal Do you have an Icon we can use for Documents?

**Comment by benjaminray3** [comment]
"Create Beautiful documents with minimal effort. Save time generating custom documents and deliver them to multiple contacts. "

**Comment by benjaminray3** [comment]
@eeghbal Can you add this to the Bottom of the page when you get some time now that we have the documents icon.

**Comment by benjaminray3** [comment]
link will go to documents page.

**Comment by truth3** [comment]
Done deal
