### ISSUE TITLE
Add Documents to "The Platform" dropdown

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#39]
We will need to add Documents to the dropdown list on release day so putting a ticket in for this..

**Comment by benjaminray3** [comment]
![screen shot 2017-03-02 at 10 44 08 pm](https://cloud.githubusercontent.com/assets/7995899/23537416/eb53959a-ff99-11e6-866c-03d7f14b2523.png)

**Comment by truth3** [comment]
@benjaminray3 @eeghbal What do you think about actually putting this up early... and on the Documents page, we can add a "Coming on 4/19/2017" in the header. 

@eeghbal This might be an interesting place to test the lead flows thing I showed you (where it pops down from the top, or side)

**Comment by benjaminray3** [comment]
@truth3 Yes I really want to do this. @eeghbal Lets work through this one.

**Comment by benjaminray3** [comment]
Closed this one
