### ISSUE TITLE
some links on this page point to ifb.com 

### ISSUE THREAD

**Issue by eeghbal** [ZerionSoftware/website#40]
https://www.zerionsoftware.com/power-user-summit-2016/

**Comment by truth3** [comment]
@eeghbal I uploaded all PDFs from the old site to the new, so we should be able to just swap out "iformbuilder" with "zerionsoftware" in the links.

**Comment by truth3** [comment]
The blog links are cleaned up and point back to the blog.zerionsoftware.com articles. This should be it.
