### ISSUE TITLE
Update CTA artwork and header graphic for GIS Professionals

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#42]
This page needs a little love to update the image with Data Collector, and also update the Hubspot CTA graphic.

https://www.zerionsoftware.com/engineering/

**Comment by eeghbal** [comment]
done - http://www.zerionsoftware.com/engineering/

**Comment by truth3** [comment]
Hey @eeghbal The CTA still has "iFormBuilder" in the image.. I was thinking we should refresh that too. What do you think?

**Comment by eeghbal** [comment]
@truth3 yep - it's in the pipeline. CTAs and e-books need to be updated (a slow & steady process)

**Comment by truth3** [comment]
@eeghbal Good deal, just going to open this back-up until we knock out the second piece and we don't lose track.
