### ISSUE TITLE
Create "Our Apps" page

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#52]
This page is not redirecting to the new website, and this is the top page on our old website generating organic traffic

https://www.iformbuilder.com/iform-apps/

**Comment by truth3** [comment]
We can reference this page.. and just focus on the Android and iOS copy of Zerion DC

https://www.iformbuilder.com/iform-apps/

App Store Links here.

https://itunes.apple.com/us/app/zerion-dc/id1204316392?mt=8

https://play.google.com/store/apps/details?id=com.zerion.apps.zeriondc&hl=en

**Comment by eeghbal** [comment]
http://www.zerionsoftware.com/zerion-apps/
