### ISSUE TITLE
Need Residential Building Inspection page

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#53]
To better support the campaign to acquire these prospects.. we need a page or section for this on the website.

**Comment by truth3** [comment]
Want to include a calculator

**Comment by truth3** [comment]
This is close.. need to clean up the artwork on the page, get a Request Trial CTA in place, and shoot the demo video

**Comment by truth3** [comment]
Add PA Builders and NAHB logo to the landing page

**Comment by truth3** [comment]
Created a dedicated sub page for the calculator, and a ranking screen like SSL labs

![screen shot 2017-04-26 at 9 46 21 am](https://cloud.githubusercontent.com/assets/7986768/25437703/3d212da6-2a65-11e7-9565-cc1b4a806deb.png)

**Comment by truth3** [comment]
calculator and dashboard is in.. need to get the PA Builders, and NAHB builders logo in place and then will close this

**Comment by benjaminray3** [comment]
- [ ] @eeghbal can you do this? PA Builder and NAHB Builders Logo

**Comment by eeghbal** [comment]
all done, @benjaminray3. removed the HTML but here it is in case we want to add later

<div id="mni-membership-636283195330388612"></div>
<script src="https://yorkbuilders.memberzone.com/Content/Script/Member.js" type="text/javascript"></script>
<script type="text/javascript">
new MNI.Widgets.Member("mni-membership-636283195330388612",{member:7255,styleTemplate:"#@id{text-align:center;position:relative}#@id .mn-widget-member-name{font-weight:700}#@id .mn-widget-member-logo{max-width:100%}"}).create();
</script>

**Comment by truth3** [comment]
Hey @eeghbal I took a quick look and NAHB logo points to the York Builders website still

**Comment by eeghbal** [comment]
thanks for catching that, @truth3 - updated.

**Comment by truth3** [comment]
Great work team @benjaminray3 @eeghbal
