### ISSUE TITLE
iFormBuilder Training recordings point back to old site

### ISSUE THREAD

**Issue by truth3** [ZerionSoftware/website#56]
This page has a list of past webinar recordings. 

https://www.zerionsoftware.com/iformbuilder-training-webinar-recordings/

The page itself links back to www.iformbuilder.com through HubSpot tracking links. We should update these to point to the proper resource on Zerion Software website.

**Comment by truth3** [comment]
@eeghbal Can you take the lead on this one?

**Comment by eeghbal** [comment]
@truth3 - all done. i'll let you take a look (may have missed something) and then close the ticket.

**Comment by truth3** [comment]
@eeghbal You might need a new nickname (Speedy Consuela)

**Comment by truth3** [comment]
@eeghbal The images on this page still point back to ifb.com website (those are actually the HS tracking links I think).

![image](https://cloud.githubusercontent.com/assets/7986768/24813987/0ecfc294-1b9e-11e7-8422-855e02571730.png)


https://www.iformbuilder.com/form-builder-101-sept-2016/?__hstc=77719563.d6d2c050d4f5ae79641dceffb3ed8635.1490738613628.1491584750763.1491589387790.9&__hssc=77719563.3.1491589387790&__hsfp=2093519150

**Comment by eeghbal** [comment]
thanks for catching that - removed the links to the images

**Comment by truth3** [comment]
Hey @eeghbal This still needs some love as I found a few video links pointing back to www.iformbuilder.com and the images all point back to ifb.com

I will copy the old artwork folder from ifb.com over to zerion so its just a matter of replacing the "iformbuilder" text in the URL with "zerionsoftware"

**Comment by truth3** [comment]
Ok, all the artwork hosted on ifb.com has been copied over

**Comment by eeghbal** [comment]
@truth3 just realized this isn't the correct recordings page (did we talk about this already?) all recordings live here: https://www.zerionsoftware.com/recordings/
do you know what the visit rate is for https://www.zerionsoftware.com/iformbuilder-training-webinar-recordings/? maybe we can remove it all together? let me know whatcha want me to do

**Comment by truth3** [comment]
Hey @eeghbal that page is not getting any traffic (1 view in 30 days). I set a redirect on this so everything goes to the "recordings" section.
