### ISSUE TITLE
Keywords for SEO in metadata

### ISSUE THREAD

**Issue by bjohannessen** [ZerionSoftware/website#58]
Just looked into our page source and noticed we didn't have any keywords to help our SEO (https://www.thoughtco.com/keywords-in-html-3469351) 

I know you are working on this, and thought this could be helpful if you weren't aware.

**Comment by truth3** [comment]
@bjohannessen What page are you looking at? Just the home page, or something else?

**Comment by truth3** [comment]
Also, not sure if you read the article or just referred to it.. but we are using the best practices by leveraging description and title along with out content and not using the old keywords tag which are devalued / penalized.

**Comment by bjohannessen** [comment]
@truth3 I was looking at our home page and looking in the keywords and meta to see if I could offer any insight to help us out. I know you guys are focusing on it a lot.

**Comment by truth3** [comment]
@bjohannessen Good deal, thanks for the follow-up
