### ISSUE TITLE
RBI - Getting started Page

### ISSUE THREAD

**Issue by benjaminray3** [ZerionSoftware/website#66]
Create a Page for Getting Started
https://www.zerionsoftware.com/residential-building-inspections/get-started

- [ ] Web Form to fill 
- [ ] Phone Number to call directly
- [ ] Graphic for Background
- [ ] After filling out the form we should give them a link to download a getting started package. (forms, blog posts, workflows, etc)
- [ ] Setup User in Dedicated Company for this. Download App
- [ ] Show Calculation Paper

**Comment by truth3** [comment]
Hey @benjaminray3 I addedd all of these things to #62 so we can keep track on all the things related to this. Gonna close this one down

**Comment by benjaminray3** [comment]
Thx @truth3
